services:
  questdb:
    image: questdb/questdb:latest
    pull_policy: always
    ports:
      - "9000:9000"
      - "9009:9009"
      - "9003:9003"
      - "8812:8812"
    volumes:
      - ./questdb:/root/.questdb
    extra_hosts:
      - "host.docker.internal:host-gateway"